---
services:
  app:
    build:
      context: './app/'
    image: 'quickguard/app'
    working_dir: '/rails/'
    command: ['./bin/rails', 'server', '-b', '0.0.0.0']
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://alloy:4318'
      RAILS_DEVELOPMENT_HOSTS: 'app'
    ports:
      - '3000:3000'
    volumes:
      - './app/:/rails/:cached'
      - 'app:/usr/local/bundle/'

  alloy:
    image: 'grafana/alloy:v1.0.0'
    command: [
      'run',
        '--server.http.listen-addr', '0.0.0.0:12345',
        '--storage.path', '/var/lib/alloy/data',
        '--stability.level', 'public-preview',
        '/etc/alloy/config.alloy'
    ]
    ports:
      - '12345:12345'
    configs:
      - source: 'alloy'
        target: '/etc/alloy/config.alloy'
    volumes:
      - './app/log/:/logs/app/'

configs:
  alloy:
    file: './config.alloy'

volumes:
  app: {}
